spring:
  datasource:
    url: jdbc:mysql://localhost/user-profile?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

data:
  profile-options:
    - email
    - password
    - name
    - country
    - homes
    - notificationsEnabled
