spring:
  data:
    mongodb:
      uri: mongodb://localhost/anber
  datasource:
    url: jdbc:mysql://localhost/anber?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

data:
  admin:
    username: ADMIN
    password: admin
    email: admin@email.com
  boolean:
    true: true
    false: false
  roles:
    admin: ROLE_ADMIN
    user: ROLE_USER
  user-profile:
    profile-options:
      - email
      - password
      - username
      - country
      - homes
      - notificationsEnabled
  search-engine:
    search-properties:
      - "cn=country"
      - "pt=provider type"
      - "pn=provider name"
      - "tn=tariff name"
      - "br=basic rate"
      - "pm=price model"
