spring:
  data:
    mongodb:
      uri: mongodb://localhost/anber
  datasource:
    url: jdbc:mysql://localhost/anber?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

data:
  admin:
    username: ADMIN
    password: admin
    email: admin@email.com
  boolean:
    true: true
    false: false
  roles:
    admin: ROLE_ADMIN
    user: ROLE_USER
  user-profile:
    profile-options:
      - email
      - password
      - username
      - country
      - homes
      - notificationsEnabled
  home:
    home-properties:
      - homeName
      - country
      - city
      - postalCode
      - type
      - sizeInSquareMeters